<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-OSVRB79" failures="1" tests="1" name="coverFox_Test.Validate_result_for_healthCare2_forSSofFailedTestcases" time="39.165" errors="0" timestamp="2024-01-03T12:46:18 IST" skipped="0">
  <testcase classname="coverFox_Test.Validate_result_for_healthCare2_forSSofFailedTestcases" name="validateResultFromTextAndBanner" time="39.165">
    <failure message="textResult &amp; bannerResult are not matched, TC is failed did not expect [49] but found [49]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: textResult & bannerResult are not matched, TC is failed did not expect [49] but found [49]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failEquals(Assert.java:1582)
at org.testng.Assert.assertNotEqualsImpl(Assert.java:157)
at org.testng.Assert.assertNotEquals(Assert.java:2198)
at coverFox_Test.Validate_result_for_healthCare2_forSSofFailedTestcases.validateResultFromTextAndBanner(Validate_result_for_healthCare2_forSSofFailedTestcases.java:86)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
    <system-out>
      <![CDATA[fetching result from text
fetching result from banner
taking ss
saving ss atC:\Users\Dell\Desktop\velocity\ss_coverfox_validateResultFromTextAndBanner_1970.01.01.05.30.00.png]]>
    </system-out>
  </testcase> <!-- validateResultFromTextAndBanner -->
  <system-out>
    <![CDATA[browser is launching
clicking on female button
clicking on next button
selecting age from dropDown
reading data from excel
clicking on next button
entering zipcode
reading data from excel
entering mobNum
reading data from excel
clicking on continue button
fetching result from text
fetching result from banner
taking ss
saving ss atC:\Users\Dell\Desktop\velocity\ss_coverfox_validateResultFromTextAndBanner_1970.01.01.05.30.00.png
closing browser]]>
  </system-out>
</testsuite> <!-- coverFox_Test.Validate_result_for_healthCare2_forSSofFailedTestcases -->
